version: '3.8'

services:
  data-service:
    build: data_service
    ports:
      - "5002:5002"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=5002
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  analysis-service:
    build: analysis_service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - DATA_SERVICE_URL=http://data-service:5002
    depends_on:
      - data-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  web-service:
    build: web_service
    ports:
      - "5004:5004"
    environment:
      - PORT=5004
      - DATA_SERVICE_URL=http://data-service:5002
      - ANALYSIS_SERVICE_URL=http://analysis-service:5003
    depends_on:
      - data-service
      - analysis-service
    volumes:
      - ./web_service/templates:/app/templates